env:
  contexts:
  - name: http://localhost:8000
    urls:
    - http://localhost:8000
    includePaths:
    - http://localhost:8000.*
    excludePaths:
    - http://localhost:8000/favicon.ico
    - http://localhost:8000/js.*
    authentication:
      verification:
        method: response
        pollFrequency: 60
        pollUnits: requests
        pollUrl: ""
        pollPostData: ""
    sessionManagement:
      method: cookie
    technology: {}
    structure: {}
  parameters: {}
jobs:
- type: passiveScan-config
  parameters: {}
- type: import
  parameters:
    type: har
    fileName: "/zap/wrk/tmp/localhost_Archive [25-06-26 13-11-37].har"
- type: passiveScan-wait
  parameters: {}
- type: activeScan
  parameters:
    context: http://localhost:8000
  policyDefinition:
    defaultStrength: low
    defaultThreshold: "off"
- type: report
  parameters:
    template: modern
    theme: console
    reportDir: /root
    reportTitle: ZAP_Report.html
  risks:
  - low
  - medium
  - high
  confidences:
  - low
  - medium
  - high
  - confirmed
  sections:
  - passingrules
  - instancecount
  - alertdetails
  - alertcount
  - params
  - chart
  - statistics

